Feature: initial home page setup
wta-fourty-love/application pull request #334
Opened 2022-07-23 16:57 UTC by Thevel0per

2022-07-24 07:22 UTC, tmtocb requested changes

2022-07-24 07:22 UTC, tmtocb commented on Gemfile
> +gem 'sprockets-rails', '~> 3.4', '>= 3.4.2'
hardcore Sprockets-Rails version

2022-07-24 07:22 UTC, tmtocb commented on Gemfile
> +gem 'dartsass-rails', '~> 0.4.0'
hardcore DartSass-Rails version

2022-07-24 07:22 UTC, tmtocb commented on Gemfile
> +  gem 'foreman'
hardcore Foreman version

2022-07-24 07:22 UTC, tmtocb commented on app/assets/stylesheets/application.scss
> +}
add empty line at the end of the file

2022-07-24 07:22 UTC, tmtocb commented on app/controllers/home_controller.rb
> +class HomeController < ApplicationController
inherit from ApiController instead of ApplicationController

2022-07-24 07:22 UTC, tmtocb commented on Gemfile
> +  gem 'foreman'
add ticket to the Project Board 'add Foreman' gem with label Gemfile

2022-07-24 07:28 UTC, tmtocb commented on Gemfile
> +  gem 'foreman'
Done: https://github.com/wta-fourty-love/application/issues/338

2022-07-24 08:17 UTC, tmtocb requested changes

2022-07-24 08:17 UTC, tmtocb commented on .gitignore
> +# Ignore dart-sass related stuff
add ticket to the Project Board 'add DartSass assets builds context to .gitignore' with labels GitHub, CSS link it to feature branch

2022-07-24 08:17 UTC, tmtocb commented on .gitignore
> +# Ignore dart-sass related stuff
Done: https://github.com/wta-fourty-love/application/issues/339

**Please resolve when you see it**

2022-07-24 08:17 UTC, tmtocb commented on bin/dev
> +
Done: https://github.com/wta-fourty-love/application/issues/340

**Please resolve when you see it**

2022-07-24 08:20 UTC, tmtocb commented on config/locales/pl.yml
> +  latest_results: "Ostatnie wyniki"
Done: https://github.com/wta-fourty-love/application/issues/341

**Please resolve when you see it**

2022-07-25 06:57 UTC, Thevel0per commented
This has been split into different tasks and features, closing.

2022-07-25 06:57 UTC, closed without merging